networks:
  default: {}

volumes:
  mysql-data: {}
  redis-data: {}
  moodle-data: {}

services:
  web:
    image: moodle:dev
    build:
      context: .
    environment:
      DB_HOST: 'mysql'
      DB_PORT: '3306'
      DB_NAME: 'moodle'
      DB_USERNAME: 'moodle'
      DB_PASSWORD: 'moodle'
      MOODLE_HOST: 'http://localhost:8080'
      REDIS_HOST: 'redis'
    networks: [default]
    ports:
      - 8080:80
    volumes:
      - type: volume
        source: moodle-data
        target: /var/www/moodledata
      - ./config.local/config.php:/var/www/moodle/config.php
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    networks: [default]
    ports:
      - 3388:3306
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
        volume:
          nocopy: true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 3s
      start_interval: 2s

  redis:
    image: redis
    networks: [default]
    volumes:
      - type: volume
        source: redis-data
        target: /data
        volume:
          nocopy: true
    command:
      - 'redis-server'
      - '--save'
      - '' # Disable persistence
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 3s
      start_interval: 2s
